function raiResizeGen(e){if(width=document.getElementById("gseRai"+e).scrollWidth,height=document.getElementById("gseRai"+e).scrollHeight,height>0&&width>0)try{parent.document!=document&&(parent.document.getElementById(window.name).width=width,parent.document.getElementById(window.name).height=height)}catch(n){return!1}}var raiTag=raiTag||{configured:!1,js_exec:!1}
void 0===raiTag.configured&&(raiTag.configured=!1),void 0===raiTag.js_exec&&(raiTag.js_exec=!1),raiTag.config=function(e){raiTag.configured||(raiTag.configured=!0,raiTag.mode=e.mode||"async",raiTag.debug=e.debug||!1,raiTag.track=e.track||!1,raiTag.localServing=e.localServing||!1,raiTag.debugURL=e.debugURL||"none",raiTag.idfa=e.idfa||"",raiTag.consentString=e.consentString||"",raiTag.pubConsent=raiTag.getCookie("pubconsent"),""!=raiTag.pubConsent&&(raiTag.pubConsent=encodeURIComponent(raiTag.pubConsent)),null!=e.hasConsent&&void 0!=e.hasConsent?raiTag.hasConsent=e.hasConsent:raiTag.hasConsent="")}
var currentScript=document.currentScript||function(){var e=document.getElementsByTagName("script")
    return e[e.length-1]}()
scriptSplit=currentScript.src.split("/")
var currentProtocol="https:",isOpera=!!window.opr&&!!opr.addons||!!window.opera||navigator.userAgent.indexOf(" OPR/")>=0,isFirefox="undefined"!=typeof InstallTrigger,isSafari=Object.prototype.toString.call(window.HTMLElement).indexOf("Constructor")>0,isIE=!!document.documentMode,isEdge=!isIE&&!!window.StyleMedia,isChrome=!!window.chrome&&!!window.chrome.webstore
raiTargetWindow=window
try{for(;raiTargetWindow!=raiTargetWindow.parent&&null==raiTargetWindow.document.getElementById("fb-root");)raiTargetWindow=raiTargetWindow.parent}catch(e){raiTargetWindow=window}raiTag.setCookie=function(e,n){var o=new Date
    exdays=90,o.setTime(o.getTime()+24*exdays*60*60*1e3)
    var a="expires="+o.toUTCString()
    document.cookie=e+"="+n+";"+a+";path=/"}
var raiTagCmpErrorText="",raiTagCmpError=null
try{void 0!==raiTargetWindow.__cmp&&raiTargetWindow.__cmp("getConsentData",null,function(e){void 0!==e&&null!=e&&void 0!==e.consentData&&(void 0===e.cmpId||30!=e.cmpId)&&(raiTag.cmpConsentData=e.consentData,raiTag.jb.push(function(){raiTag.setCookie("localpubconsent",e.consentData)}),raiTag.jb.push(function(){raiTag.setCookie("localeuconsent",e.consentData)}))})}catch(e){raiTagCmpError=e,raiTagCmpErrorText="unfriendly iframe"}try{raiTargetWindowDocument=raiTargetWindow.document}catch(e){raiTargetWindowDocument=document}if(raiTag.sendCookieSync=function(e,n,o){null==raiTargetWindowDocument.getElementById("raiCsync")&&(raIfr=document.createElement("IFRAME"),raIfr.setAttribute("src","https://sync.richaudience.com/dcf3528a0b8aa83634892d50e91c306e/?ord="+Math.floor(1e13*Math.random())+"&pubconsent="+e+"&euconsent="+n+"&hasConsent="+o),raIfr.id="raiCsync",raIfr.style.width="0px",raIfr.style.height="0px",raIfr.style.borderStyle="none",raIfr.style.frameBorder=0,raIfr.style.cssFloat="left",raIfr.scrolling="no",raiTargetWindowDocument.body.appendChild(raIfr))},raiTag.getCookie=function(e){for(var n=e+"=",o=decodeURIComponent(document.cookie),a=o.split(";"),t=0;t<a.length;t++){for(var i=a[t];" "==i.charAt(0);)i=i.substring(1)
    if(0==i.indexOf(n))return i.substring(n.length,i.length)}return""},raiTag.renderCreative=function(e,n){"async"==raiTag.mode&&(window["raiHtml"+e]='<!DOCTYPE html><html style="margin: 0px;padding: 0px;border: 0px;"><head><meta http-equiv="X-UA-Compatible" content="IE=EDGE" /><meta charset="UTF-8" /><script>var inDapIF=inDapMgrIf=inDapRai=true;</script></head><body style="border:0px;margin:0px;padding:0px;overflow:hidden"><div id="gseRai'+e+'">'+n+"</div></body></html>",window["d"+e]=document.getElementById("raiIf"+e).contentDocument||document.getElementById("raiIf"+e).contentWindow.document,window["d"+e].open(),window["d"+e].write(window["raiHtml"+e]),window["d"+e].close())},raiTag.fillSlots=function(e,n){if("async"==raiTag.mode){var o=""
    ""!=raiTag.getCookie("pubconsent")?o+="&pubConsent="+encodeURIComponent(raiTag.getCookie("pubconsent")):""!=raiTag.getCookie("eupubconsent")?o+="&pubConsent="+encodeURIComponent(raiTag.getCookie("eupubconsent")):""!=raiTag.getCookie("localpubconsent")?o+="&pubConsent="+encodeURIComponent(raiTag.getCookie("localpubconsent")):void 0!==raiTag.cmpConsentData&&(o+="&pubConsent="+encodeURIComponent(raiTag.cmpConsentData)),""!=raiTag.getCookie("euconsent")?o+="&euconsent="+encodeURIComponent(raiTag.getCookie("euconsent")):""!=raiTag.getCookie("localeuconsent")?o+="&euconsent="+encodeURIComponent(raiTag.getCookie("localeuconsent")):void 0!==raiTag.cmpConsentData&&(o+="&euconsent="+encodeURIComponent(raiTag.cmpConsentData)),""!==raiTag.hasConsent&&(o+="&hasConsent="+raiTag.hasConsent),""!=raiTag.consentString&&(o+="&consentString="+raiTag.consentString)
    try{for(;topParent!=topParent.window.parent&&null==topParent.document.getElementById("fb-root");)topParent=topParent.window.parent
        var a=topParent.screen.width,t=topParent.screen.height,i=topParent.innerWidth,r=topParent.innerHeight,c=topParent.outerWidth,s=topParent.outerHeight}catch(g){topParent=window
        var a=-1,t=-1,a=-1,t=-1,i=-1,r=-1,c=-1,s=-1}var d=i*r
    srcSlots=currentProtocol+(raiTag.localServing?raiTag.debugURL+"/srs/":"//s.richaudience.com/srs/")+e+"/ads.js"+(raiTag.debug?"?raiDbg=true":"?raiDbg=false")+"&wscs="+a+"&hscs="+t+"&tscs="+d+"&inw="+i+"&inh="+r+"&wou="+c+"&hou="+s+o,void 0!==window["raTestRads"+e]&&(srcSlots+="&tr="+window["raTestRads"+e]),scriptSlots=document.createElement("script"),scriptSlots.type="text/javascript",scriptSlots.src=srcSlots,document.body.appendChild(scriptSlots)}},raiTag.fillSlot=function(e,n){csyncPubConsent="",""!=raiTag.getCookie("pubconsent")?csyncPubConsent=raiTag.getCookie("pubconsent"):""!=raiTag.getCookie("eupubconsent")?csyncPubConsent=raiTag.getCookie("eupubconsent"):""!=raiTag.getCookie("localpubconsent")?csyncPubConsent=raiTag.getCookie("localpubconsent"):void 0!==raiTag.cmpConsentData&&(csyncPubConsent=raiTag.cmpConsentData),csyncEuConsent="",""!=raiTag.getCookie("euconsent")?csyncEuConsent=raiTag.getCookie("euconsent"):""!=raiTag.getCookie("localeuconsent")?csyncEuConsent=raiTag.getCookie("localeuconsent"):""!=raiTag.consentString?csyncEuConsent=raiTag.consentString:void 0!==raiTag.cmpConsentData&&(csyncEuConsent=raiTag.cmpConsentData),csyncHasConsent="",""!==raiTag.hasConsent&&(csyncHasConsent=raiTag.hasConsent),raiTag.sendCookieSync(csyncPubConsent,csyncEuConsent,csyncHasConsent)
    var o=window
    try{for(;o!=o.window.parent&&null==o.document.getElementById("fb-root");)o=o.window.parent
        var a=o.screen.width,t=o.screen.height,i=o.innerWidth,r=o.innerHeight,c=o.outerWidth,s=o.outerHeight}catch(g){o=window
        var a=-1,t=-1,a=-1,t=-1,i=-1,r=-1,c=-1,s=-1}if("async"==raiTag.mode){window["raiIframe"+e]=document.createElement("iframe"),void 0!=n[0]&&void 0!=n[0][0]&&void 0!=n[0][1]?(window["raiIframe"+e].width=n[0][0],window["raiIframe"+e].height=n[0][1]):(window["raiIframe"+e].width="0",window["raiIframe"+e].height="0"),window["raiIframe"+e].srcdoc="",window["raiIframe"+e].setAttribute("frameborder","0"),window["raiIframe"+e].id="raiIf"+e
        var d=""
        ""!=raiTag.getCookie("pubconsent")?d+="&pubConsent="+encodeURIComponent(raiTag.getCookie("pubconsent")):""!=raiTag.getCookie("eupubconsent")?d+="&pubConsent="+encodeURIComponent(raiTag.getCookie("eupubconsent")):""!=raiTag.getCookie("localpubconsent")?d+="&pubConsent="+encodeURIComponent(raiTag.getCookie("localpubconsent")):void 0!==raiTag.cmpConsentData&&(d+="&pubConsent="+encodeURIComponent(raiTag.cmpConsentData)),""!=raiTag.getCookie("euconsent")?d+="&euconsent="+encodeURIComponent(raiTag.getCookie("euconsent")):""!=raiTag.getCookie("localeuconsent")?d+="&euconsent="+encodeURIComponent(raiTag.getCookie("localeuconsent")):void 0!==raiTag.cmpConsentData&&(d+="&euconsent="+encodeURIComponent(raiTag.cmpConsentData)),""!==raiTag.hasConsent&&(d+="&hasConsent="+raiTag.hasConsent),""!=raiTag.consentString&&(d+="&consentString="+raiTag.consentString)
        var u=i*r
        window["raiHtml"+e]='<!DOCTYPE html><html style="margin: 0px;padding: 0px;border: 0px;"><head><meta http-equiv="X-UA-Compatible" content="IE=EDGE" /><meta charset="UTF-8" /><script>var inDapIF=inDapMgrIf=inDapRai=true;</script></head><body style="border:0px;margin:0px;padding:0px;overflow:hidden"><div id="gseRai'+e+'"><script src="'+currentProtocol+(raiTag.localServing?raiTag.debugURL+"/srv/":"//s.richaudience.com/srv/")+e+"/ads.js"+(raiTag.debug?"?raiDbg=true":"?raiDbg=false")+"&wscs="+a+"&hscs="+t+"&tscs="+u+"&inw="+i+"&inh="+r+"&wou="+c+"&hou="+s+d+'"></script></div></body></html>',document.getElementById("gseRai"+e).appendChild(window["raiIframe"+e]),isFirefox||isIE?document.addEventListener?window.addEventListener("load",function(){window["d"+e]=window["raiIframe"+e].contentDocument||window["raiIframe"+e].contentWindow.document,window["d"+e].open(),window["d"+e].write(window["raiHtml"+e]),window["d"+e].close()}):window.attachEvent("onload",function(){window["d"+e]=window["raiIframe"+e].contentDocument||window["raiIframe"+e].contentWindow.document,window["d"+e].open(),window["d"+e].write(window["raiHtml"+e]),window["d"+e].close()}):(window["d"+e]=window["raiIframe"+e].contentDocument||window["raiIframe"+e].contentWindow.document,window["d"+e].open(),window["d"+e].write(window["raiHtml"+e]),window["d"+e].close())}else if("sync"==raiTag.mode){var d=""
        ""!=raiTag.getCookie("pubconsent")?d+="&pubConsent="+encodeURIComponent(raiTag.getCookie("pubconsent")):""!=raiTag.getCookie("eupubconsent")?d+="&pubConsent="+encodeURIComponent(raiTag.getCookie("eupubconsent")):""!=raiTag.getCookie("localpubconsent")?d+="&pubConsent="+encodeURIComponent(raiTag.getCookie("localpubconsent")):void 0!==raiTag.cmpConsentData&&(d+="&pubConsent="+encodeURIComponent(raiTag.cmpConsentData)),""!=raiTag.getCookie("euconsent")?d+="&euconsent="+encodeURIComponent(raiTag.getCookie("euconsent")):""!=raiTag.getCookie("localeuconsent")?d+="&euconsent="+encodeURIComponent(raiTag.getCookie("localeuconsent")):void 0!==raiTag.cmpConsentData&&(d+="&euconsent="+encodeURIComponent(raiTag.cmpConsentData)),""!==raiTag.hasConsent&&(d+="&hasConsent="+raiTag.hasConsent),""!=raiTag.consentString&&(d+="&consentString="+raiTag.consentString),window["raiScript"+e]=document.createElement("script"),window["raiScript"+e].type="text/javascript",window["raiScript"+e].src=currentProtocol+(raiTag.localServing?raiTag.debugURL+"/srv/":"//s.richaudience.com/srv/")+e+"/ads.js"+(raiTag.debug?"?raiDbg=true":"?raiDbg=false")+"&wscs="+a+"&hscs="+t+"&tscs="+u+"&inw="+i+"&inh="+r+"&wou="+c+"&hou="+s+d,document.getElementById("gseRai"+e).appendChild(window["raiScript"+e])}},raiTag.fillSlotApp=function(e,n){var o="",a=""
    ""!=raiTag.hasConsent&&(o+="&hasConsent="+raiTag.hasConsent),""!=raiTag.consentString&&(o+="&consentString="+raiTag.consentString),""!=raiTag.idfa&&(a+="&fs_idfa="+raiTag.idfa),window["raiScript"+e]=document.createElement("script"),window["raiScript"+e].type="text/javascript",window["raiScript"+e].src=currentProtocol+(raiTag.localServing?raiTag.debugURL+"/appsrv/":"//s.richaudience.com/appsrv/")+e+"/ads.js"+(raiTag.debug?"?raiDbg=true":"?raiDbg=false")+o+a+(null!=n&&void 0!==n[0]?"&dwidth="+n[0]:"")+(null!=n&&void 0!==n[1]?"&	="+n[1]:""),document.getElementById("gseRai"+e).appendChild(window["raiScript"+e])},raiTag.fillHi=function(e){if(csyncPubConsent="",""!=raiTag.getCookie("pubconsent")?csyncPubConsent=raiTag.getCookie("pubconsent"):""!=raiTag.getCookie("eupubconsent")?csyncPubConsent=raiTag.getCookie("eupubconsent"):""!=raiTag.getCookie("localpubconsent")?csyncPubConsent=raiTag.getCookie("localpubconsent"):void 0!==raiTag.cmpConsentData&&(csyncPubConsent=raiTag.cmpConsentData),csyncEuConsent="",""!=raiTag.getCookie("euconsent")?csyncEuConsent=raiTag.getCookie("euconsent"):""!=raiTag.getCookie("localeuconsent")?csyncEuConsent=raiTag.getCookie("localeuconsent"):""!=raiTag.consentString?csyncEuConsent=raiTag.consentString:void 0!==raiTag.cmpConsentData&&(csyncEuConsent=raiTag.cmpConsentData),csyncHasConsent="",""!==raiTag.hasConsent&&(csyncHasConsent=raiTag.hasConsent),raiTag.sendCookieSync(csyncPubConsent,csyncEuConsent,csyncHasConsent),null==raiTargetWindow.document.getElementById("raiHITag"+e)&&!(void 0!==raiTargetWindow.pnetSkinExclu&&0!=raiTargetWindow.pnetSkinExclu||"undefined"!=typeof pnetSkinExclu&&0!=pnetSkinExclu||void 0!==raiTargetWindow.raiHIExclu&&0!=raiTargetWindow.raiHIExclu||"undefined"!=typeof raiHIExclu&&0!=raiHIExclu||"undefined"!=typeof pnetTarget&&-1!=pnetTarget.indexOf("gCampaign=noSkin"))){raProtocol="https:",raiHITag=raiTargetWindow.document.createElement("script"),raiHITag.id="raiHITag"+e,raiHITag.setAttribute("type","text/javascript"),raHISrc=raProtocol+(raiTag.localServing?raiTag.debugURL+"/hi/":"//s.richaudience.com/hi/")+e+"/ads.js?rnd="+Math.floor(99999999*Math.random()+1),"undefined"!=typeof screen&&"undefiend"!=typeof screen.width&&"undefiend"!=typeof screen.height&&(raHISrc=raHISrc+"&sw="+encodeURIComponent(screen.width)+"&sh="+encodeURIComponent(screen.height)),"undefined"!=typeof raiTarget&&(raHISrc=raHISrc+"&target="+encodeURIComponent(raiTarget)),raHISrc=raHISrc+"&ipmref="+encodeURIComponent(document.location.href)
    var n=""
    ""!=raiTag.getCookie("pubconsent")?n+="&pubConsent="+encodeURIComponent(raiTag.getCookie("pubconsent")):""!=raiTag.getCookie("eupubconsent")?n+="&pubConsent="+encodeURIComponent(raiTag.getCookie("eupubconsent")):""!=raiTag.getCookie("localpubconsent")?n+="&pubConsent="+encodeURIComponent(raiTag.getCookie("localpubconsent")):void 0!==raiTag.cmpConsentData&&(n+="&pubConsent="+encodeURIComponent(raiTag.cmpConsentData)),""!=raiTag.getCookie("euconsent")?n+="&euconsent="+encodeURIComponent(raiTag.getCookie("euconsent")):""!=raiTag.getCookie("localeuconsent")?n+="&euconsent="+encodeURIComponent(raiTag.getCookie("localeuconsent")):void 0!==raiTag.cmpConsentData&&(n+="&euconsent="+encodeURIComponent(raiTag.cmpConsentData)),raHISrc+=n,"undefined"!=typeof hasConsent&&""!=hasConsent&&(raHISrc+="&hasConsent="+hasConsent),"undefined"!=typeof consentString&&""!=consentString&&(raHISrc+="&consentString="+consentString),raiHITag.src=raHISrc,raiTargetWindow.document.body.appendChild(raiHITag)}},0==raiTag.js_exec){if(raiTag.js_exec=!0,void 0!==raiTag.jb&&raiTag.jb.length>0)for(;raiTag.jb.length>0;)raiTag.jb.shift()()
    void 0===raiTag.jb&&(raiTag.jb={}),raiTag.jb.push=function(e){e()}}
